apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aro.fullname" . }}-config
data:
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- if .Values.redis.enabled }}
  ARO_REDIS_URL: "redis://{{ include "aro.fullname" . }}-redis:6379"
{{- end }}
{{- if .Values.clamav.enabled }}
  ARO_CLAMAV_ADDRESS: "{{ include "aro.fullname" . }}-clamav:{{ .Values.clamav.port }}"
{{- end }}
