apiVersion: v1
kind: Service
metadata:
  name: {{ include "aro.fullname" . }}-api
spec:
  selector:
    app.kubernetes.io/name: {{ include "aro.fullname" . }}-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
