use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PluginAuthConfig {
    pub auth_type: String, // "oauth2" | "api_key" | "pat"
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_name: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub scopes: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub documentation_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_label: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MarketplacePlugin {
    pub id: String,
    pub name: String,
    pub version: String,
    pub description: String,
    pub author: String,
    pub category: String,
    pub icon: String,
    pub repository: String,
    pub keywords: Vec<String>,
    pub mcp_servers_count: usize,
    pub skills_count: usize,
    pub installed: bool,
    pub sample_skills: Vec<String>,
    pub sample_mcp_servers: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth: Option<PluginAuthConfig>,
}

pub fn get_curated_marketplace() -> Vec<MarketplacePlugin> {
    vec![
        MarketplacePlugin {
            id: "filesystem-tools".to_string(),
            name: "Filesystem & Workspace".to_string(),
            version: "1.0.0".to_string(),
            description: "Standard filesystem operations, tree inspection, and search via Model Context Protocol.".to_string(),
            author: "ARO Ecosystem".to_string(),
            category: "Filesystem".to_string(),
            icon: "📁".to_string(),
            repository: "https://github.com/agentplugins/filesystem-tools".to_string(),
            keywords: vec!["fs".to_string(), "workspace".to_string(), "files".to_string()],
            mcp_servers_count: 1,
            skills_count: 2,
            installed: false,
            sample_skills: vec!["workspace-explorer".to_string(), "file-finder".to_string()],
            sample_mcp_servers: vec!["local-fs".to_string()],
            auth: None,
        },
        MarketplacePlugin {
            id: "web-search-tools".to_string(),
            name: "Web Search & Fetch".to_string(),
            version: "1.2.0".to_string(),
            description: "Extract clean web page content, search live search engines, and fetch public documentation.".to_string(),
            author: "ARO Ecosystem".to_string(),
            category: "Web & Research".to_string(),
            icon: "🌐".to_string(),
            repository: "https://github.com/agentplugins/web-search-tools".to_string(),
            keywords: vec!["web".to_string(), "search".to_string(), "scraper".to_string()],
            mcp_servers_count: 1,
            skills_count: 1,
            installed: false,
            sample_skills: vec!["documentation-crawler".to_string()],
            sample_mcp_servers: vec!["web-fetcher".to_string()],
            auth: None,
        },
        MarketplacePlugin {
            id: "git-assistant".to_string(),
            name: "Git Assistant".to_string(),
            version: "1.1.0".to_string(),
            description: "Git repository automation, staging, commit formatting, and branch synchronization.".to_string(),
            author: "ARO Ecosystem".to_string(),
            category: "Development".to_string(),
            icon: "🐈".to_string(),
            repository: "https://github.com/agentplugins/git-assistant".to_string(),
            keywords: vec!["git".to_string(), "version-control".to_string(), "commits".to_string()],
            mcp_servers_count: 1,
            skills_count: 2,
            installed: false,
            sample_skills: vec!["smart-commit".to_string(), "branch-cleaner".to_string()],
            sample_mcp_servers: vec!["git-mcp".to_string()],
            auth: None,
        },
        MarketplacePlugin {
            id: "sqlite-database".to_string(),
            name: "SQLite & SQL Explorer".to_string(),
            version: "1.0.1".to_string(),
            description: "Query, introspect schemas, and manage SQLite databases securely via MCP.".to_string(),
            author: "ARO Ecosystem".to_string(),
            category: "Database".to_string(),
            icon: "🗄️".to_string(),
            repository: "https://github.com/agentplugins/sqlite-database".to_string(),
            keywords: vec!["sqlite".to_string(), "sql".to_string(), "database".to_string()],
            mcp_servers_count: 1,
            skills_count: 1,
            installed: false,
            sample_skills: vec!["schema-auditor".to_string()],
            sample_mcp_servers: vec!["sqlite-server".to_string()],
            auth: None,
        },
        MarketplacePlugin {
            id: "python-analytics".to_string(),
            name: "Python Analytics".to_string(),
            version: "1.0.0".to_string(),
            description: "Run Python scripts, compute statistical calculations, and transform data frames.".to_string(),
            author: "ARO Ecosystem".to_string(),
            category: "Data & Code".to_string(),
            icon: "🐍".to_string(),
            repository: "https://github.com/agentplugins/python-analytics".to_string(),
            keywords: vec!["python".to_string(), "data".to_string(), "analytics".to_string()],
            mcp_servers_count: 1,
            skills_count: 2,
            installed: false,
            sample_skills: vec!["data-summarizer".to_string(), "chart-generator".to_string()],
            sample_mcp_servers: vec!["python-kernel".to_string()],
            auth: None,
        },
        MarketplacePlugin {
            id: "code-reviewer".to_string(),
            name: "Code Review & Security".to_string(),
            version: "1.3.0".to_string(),
            description: "Automated architectural code reviews, linting validation, and security vulnerability scanning.".to_string(),
            author: "ARO Ecosystem".to_string(),
            category: "Code Quality".to_string(),
            icon: "🛡️".to_string(),
            repository: "https://github.com/agentplugins/code-reviewer".to_string(),
            keywords: vec!["security".to_string(), "review".to_string(), "audit".to_string()],
            mcp_servers_count: 1,
            skills_count: 2,
            installed: false,
            sample_skills: vec!["security-audit".to_string(), "architecture-check".to_string()],
            sample_mcp_servers: vec!["code-reviewer-server".to_string()],
            auth: None,
        },
        MarketplacePlugin {
            id: "google-workspace".to_string(),
            name: "Google Workspace & Drive".to_string(),
            version: "1.0.0".to_string(),
            description: "Integrate Google Drive, Docs, Gmail, and Calendar into agent workflows via MCP.".to_string(),
            author: "Google & ARO Ecosystem".to_string(),
            category: "Productivity".to_string(),
            icon: "📑".to_string(),
            repository: "https://github.com/agentplugins/google-workspace".to_string(),
            keywords: vec![
                "google".to_string(),
                "workspace".to_string(),
                "drive".to_string(),
                "docs".to_string(),
                "gmail".to_string(),
            ],
            mcp_servers_count: 1,
            skills_count: 2,
            installed: false,
            sample_skills: vec![
                "workspace-organizer".to_string(),
                "calendar-scheduler".to_string(),
            ],
            sample_mcp_servers: vec!["google-workspace-mcp".to_string()],
            auth: Some(PluginAuthConfig {
                auth_type: "oauth2".to_string(),
                provider_name: Some("Google Workspace / Gmail".to_string()),
                scopes: vec![
                    "https://www.googleapis.com/auth/userinfo.email".to_string(),
                    "https://www.googleapis.com/auth/userinfo.profile".to_string(),
                    "https://www.googleapis.com/auth/gmail.modify".to_string(),
                    "https://www.googleapis.com/auth/drive".to_string(),
                ],
                instructions: Some("Connectez un ou plusieurs comptes Google (ex: Personnel et Travail) pour permettre à ARO d'accéder à Gmail, Drive et Google Docs.".to_string()),
                documentation_url: Some("https://developers.google.com/identity/protocols/oauth2".to_string()),
                default_label: Some("Compte Google".to_string()),
            }),
        },
        MarketplacePlugin {
            id: "openai-ecosystem".to_string(),
            name: "OpenAI Assistants & Models".to_string(),
            version: "1.2.0".to_string(),
            description: "Connect OpenAI Assistants API, prompt evaluations, embeddings, and token analysis via MCP.".to_string(),
            author: "OpenAI & ARO Ecosystem".to_string(),
            category: "AI & Models".to_string(),
            icon: "🤖".to_string(),
            repository: "https://github.com/agentplugins/openai-ecosystem".to_string(),
            keywords: vec![
                "openai".to_string(),
                "chatgpt".to_string(),
                "assistants".to_string(),
                "embeddings".to_string(),
            ],
            mcp_servers_count: 1,
            skills_count: 1,
            installed: false,
            sample_skills: vec!["prompt-optimizer".to_string()],
            sample_mcp_servers: vec!["openai-mcp".to_string()],
            auth: Some(PluginAuthConfig {
                auth_type: "api_key".to_string(),
                provider_name: Some("OpenAI".to_string()),
                scopes: vec![],
                instructions: Some("Saisissez votre clé secrète d'API OpenAI (sk-...) pour permettre aux outils du plugin d'interagir avec les modèles d'OpenAI.".to_string()),
                documentation_url: Some("https://platform.openai.com/api-keys".to_string()),
                default_label: Some("Clé OpenAI".to_string()),
            }),
        },
        MarketplacePlugin {
            id: "github-developer".to_string(),
            name: "GitHub Developer Suite".to_string(),
            version: "1.1.0".to_string(),
            description: "Inspect repositories, triage Pull Requests, manage issues, and audit GitHub Actions workflows via MCP.".to_string(),
            author: "GitHub & ARO Ecosystem".to_string(),
            category: "Development".to_string(),
            icon: "🐙".to_string(),
            repository: "https://github.com/agentplugins/github-developer".to_string(),
            keywords: vec![
                "github".to_string(),
                "git".to_string(),
                "pull-request".to_string(),
                "issues".to_string(),
                "actions".to_string(),
            ],
            mcp_servers_count: 1,
            skills_count: 2,
            installed: false,
            sample_skills: vec!["pr-reviewer".to_string(), "issue-triager".to_string()],
            sample_mcp_servers: vec!["github-mcp".to_string()],
            auth: Some(PluginAuthConfig {
                auth_type: "oauth2".to_string(),
                provider_name: Some("GitHub".to_string()),
                scopes: vec!["repo".to_string(), "read:user".to_string(), "user:email".to_string()],
                instructions: Some("Connectez un ou plusieurs comptes GitHub (ou utilisez un Personal Access Token) pour inspecter vos dépôts et PRs.".to_string()),
                documentation_url: Some("https://github.com/settings/tokens".to_string()),
                default_label: Some("Compte GitHub".to_string()),
            }),
        },
        MarketplacePlugin {
            id: "slack-workspace".to_string(),
            name: "Slack Collaboration Hub".to_string(),
            version: "1.0.0".to_string(),
            description: "Post messages, query conversation channels, and automate team standup summaries via MCP.".to_string(),
            author: "Slack & ARO Ecosystem".to_string(),
            category: "Communication".to_string(),
            icon: "💬".to_string(),
            repository: "https://github.com/agentplugins/slack-workspace".to_string(),
            keywords: vec![
                "slack".to_string(),
                "messaging".to_string(),
                "channels".to_string(),
                "collaboration".to_string(),
            ],
            mcp_servers_count: 1,
            skills_count: 1,
            installed: false,
            sample_skills: vec!["standup-reporter".to_string()],
            sample_mcp_servers: vec!["slack-mcp".to_string()],
            auth: Some(PluginAuthConfig {
                auth_type: "oauth2".to_string(),
                provider_name: Some("Slack".to_string()),
                scopes: vec!["chat:write".to_string(), "channels:read".to_string()],
                instructions: Some("Connectez votre espace de travail Slack pour permettre l'envoi de messages et la lecture des canaux d'équipe.".to_string()),
                documentation_url: Some("https://api.slack.com/authentication".to_string()),
                default_label: Some("Espace Slack".to_string()),
            }),
        },
    ]
}
